apiVersion: v1
kind: Secret
metadata:
  name: github-app-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  type: git
  url: https://github.com/homedevlabs
  githubAppID: "2741884"
  githubAppInstallationID: "106482504"
  githubAppPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEArVKsiXvZGZHZSiOjJdOXUgt6fDVXAFrFCt9OQgfnMWM8P+yC
    EevcoYeQi5msgpWebF9JyAWvCDQuCyPBysuLuKh++B7E8mlUXFPvHTpSuZhHlXY8
    H3BSxcwfh7bGEF/OpiNmgMrxgH+nWTo0AX0PYEFLTd68Qeb+oFLgHFZGDrhg2LIr
    15WAYypA+dTf9M9rM8sadtxOIAPgPaXV2qutEgOTuUvmFs/ix41NIaA2vHWX/vLg
    oA93xY8H4n9OcG7Ad9T/uCMXgOJ8skOZubCHheJvorZNk0UvQSSkbLdBWsMEAmP4
    BEaCpAcY27NMM2nemFldHY68dRjmda/kCPAxUwIDAQABAoIBADxNsX48OvLsjd9/
    urnkfperKrigjl6vNjNsMnxC56uFTWcoULEPkToaQq5vj1f32qD2HmObpqSCEysJ
    C9oVK83ZwiNuATQedZ2SDnXq3vF4DB/yfUSq/gGX3biIXS1BSFMBqh5RfekpgP5I
    g+OosXrZ/Otg/bsoNZtuek8hrUpdRa4abghFJCa/rtr4uwuuZv9aZpxUDr9xBakC
    IvlIx1wW2XLML61tRW3siYHj7wPdM53+UUYIhX08468ccSHo6NY5u2AfB+l0dHem
    eVsQopz24+vmmi9TQ0H+SlZS+/DDBxqmfeugmM5gbAJbcxWYQJN/rVaYis3mTFSw
    p+m9kzECgYEA1SRs7FWK9DPEnvsEfB4R4V2Dyq43KUxMEizUnBqEMSED8AHA0UmB
    UihbKLfWOPA4s+7gy+N+yfBb9Aokz0vXSNtA0BclqHCsU4vuPglVFlti6l6TlvBY
    rHNik2+28zYWGYvUAGr9JlSk9m1rEUddTRV+S1cD4XIbjcVFwXvxp/cCgYEA0CyI
    p2sDM0pSSCBdfedLmS0MWO/XstUz2hQNj2W2LFTlFNhUmiOh7XqYj+WEjY06oPqP
    baxyAxJQxidYilf3YhC6VxUeTm6VE0z3a8swpeSU15MC31i90nrABPIp162LkqvC
    xkn/gnLkXUZAn91CXd6OREtcM9Xd6HO7esqMAoUCgYBAV6aqEYjI/3ezpoNMFKfB
    KMHIRZ9RUD8GnZHxLfAKBLVzlpPmmhH4A0bBm/2HYr07VDl4U0zLGUwo94b1LSfo
    TofaSaKMnrbm4a8h+x88iInrxnE3d4bNSGfRqj/IW+OAAr4VAiPnllXWLmHL7Yc0
    5fAiPjplrFS1D4BnUEs7MQKBgAJKSyKUYc+hpLAYcw7ciY9g2H7t/JCCGfTvPYrz
    UoLAWFjXXG7pr3FeZOlIXCH2iMuWlhddy09PV0YmzqmO+DDDAFnO6KtyOf+hXCN6
    c8mPbzfD7UcpwcTcBtrHE0DFLwDpFNZ7n+z+eJayHCnmFEHWHfiQX65OTwespkZe
    jhXFAoGAYwmN27fH1pRvEAv1C5K2V+84Mt8Fm4M7OdezddiI+rvmrx8DfAGLH45s
    vfkpPwaIB0muQagbgp6PH4/JkMd3JaURn9b4XHTTmJ/cfdTuHUddJ3SAdy8e4+0O
    NWWjYItPyyQ0JNL6jHXi9mP4K7wxngvfXQHLJK7hyDOrA4cRvV0=
    -----END RSA PRIVATE KEY-----
