apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app-config
  namespace: backstage
data:
  entities.yaml: |
    ---
    apiVersion: backstage.io/v1alpha1
    kind: System
    metadata:
      name: examples
    spec:
      owner: guests
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: example-website
    spec:
      type: website
      lifecycle: experimental
      owner: guests
      system: examples
      providesApis: [example-grpc-api]
    ---
    apiVersion: backstage.io/v1alpha1
    kind: API
    metadata:
      name: example-grpc-api
    spec:
      type: grpc
      lifecycle: experimental
      owner: guests
      system: examples
      definition: |
        syntax = "proto3";

        service Exampler {
          rpc Example (ExampleMessage) returns (ExampleMessage) {};
        }

        message ExampleMessage {
          string example = 1;
        };
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: neto007
    spec:
      profile:
        displayName: Neto
        picture: https://github.com/neto007.png
      memberOf: [guest]
  app-config.yaml: |
    app:
      title: Backstage
      baseUrl: https://backstage.superlab.app

    organization:
      name: My Company

    backend:
      baseUrl: https://backstage.superlab.app

      listen:
        port: 7007
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: https://backstage.superlab.app
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
          database: ${POSTGRES_DB}

    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_ID}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY}
              clientId: ${AUTH_GITHUB_CLIENT_ID}
              clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

    auth:
      environment: production
      providers:
        github:
          production:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
            signIn:
              resolvers:
                - resolver: usernameMatchingUserEntityName

    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Resource, Location, User, Group]
      providers:
        githubOrg:
          production:
            orgs: [ homedevlabs ]
            schedule:
              frequency: { minutes: 30 }
              timeout: { minutes: 3 }
              initialDelay: { seconds: 15 }
      locations:
        - type: file
          target: /app/entities.yaml
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    techdocs:
      builder: 'local'
      generator:
        runIn: 'docker'
      publisher:
        type: 'local'

    permission:
      enabled: true
