apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backstage-apps
  namespace: argocd
spec:
  generators:
  - scmProvider:
      github:
        organization: homedevlabs
        api: https://api.github.com
        # Usando o Secret de credenciais do GitHub App que já configuramos
        appSecretName: github-app-repo-creds
      filters:
      - repositoryMatch: .*
        pathsExist: [k8s]
  template:
    metadata:
      name: '{{repository}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/homedevlabs/{{repository}}.git'
        targetRevision: '{{branch}}'

        path: k8s
      destination:
        server: https://kubernetes.default.svc
        namespace: backstage

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
